//
//新版较为特殊,这里都是只表达数据包结构
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: edotcs.proto

package drpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// =============================
// 初始化消息注册
// =============================
// 注册消息
type New_Type struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        string `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`               // 注册消息类型
	Name        string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`               // 注册消息名称
	Description string `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"` // 注册消息描述
}

func (x *New_Type) Reset() {
	*x = New_Type{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *New_Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*New_Type) ProtoMessage() {}

func (x *New_Type) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use New_Type.ProtoReflect.Descriptor instead.
func (*New_Type) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{0}
}

func (x *New_Type) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *New_Type) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *New_Type) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 消息列表
type TypeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Types []*New_Type `protobuf:"bytes,1,rep,name=Types,proto3" json:"Types,omitempty"` // 注册消息列表
}

func (x *TypeList) Reset() {
	*x = TypeList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeList) ProtoMessage() {}

func (x *TypeList) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeList.ProtoReflect.Descriptor instead.
func (*TypeList) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{1}
}

func (x *TypeList) GetTypes() []*New_Type {
	if x != nil {
		return x.Types
	}
	return nil
}

// 插件初始化第一个发送的数据包
type Plugin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name               string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`                                                             // 插件名称
	Author             string   `protobuf:"bytes,2,opt,name=Author,proto3" json:"Author,omitempty"`                                                         //插件作者
	Version            *Version `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`                                                       //插件版本
	Recommendation     *string  `protobuf:"bytes,4,opt,name=recommendation,proto3,oneof" json:"recommendation,omitempty"`                                   //插件介绍
	MenuWord           *string  `protobuf:"bytes,5,opt,name=menu_word,json=menuWord,proto3,oneof" json:"menu_word,omitempty"`                               // 插件菜单关键词(以htp为例, .htp )
	MenuRecommendation *string  `protobuf:"bytes,6,opt,name=menu_recommendation,json=menuRecommendation,proto3,oneof" json:"menu_recommendation,omitempty"` // 插件菜单关键词介绍
}

func (x *Plugin) Reset() {
	*x = Plugin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plugin) ProtoMessage() {}

func (x *Plugin) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plugin.ProtoReflect.Descriptor instead.
func (*Plugin) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{2}
}

func (x *Plugin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plugin) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Plugin) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *Plugin) GetRecommendation() string {
	if x != nil && x.Recommendation != nil {
		return *x.Recommendation
	}
	return ""
}

func (x *Plugin) GetMenuWord() string {
	if x != nil && x.MenuWord != nil {
		return *x.MenuWord
	}
	return ""
}

func (x *Plugin) GetMenuRecommendation() string {
	if x != nil && x.MenuRecommendation != nil {
		return *x.MenuRecommendation
	}
	return ""
}

// 玩家消息
type Player_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player  string `protobuf:"bytes,1,opt,name=Player,proto3" json:"Player,omitempty"`   // 玩家名
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"` // 玩家消息
}

func (x *Player_Message) Reset() {
	*x = Player_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player_Message) ProtoMessage() {}

func (x *Player_Message) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player_Message.ProtoReflect.Descriptor instead.
func (*Player_Message) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{3}
}

func (x *Player_Message) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (x *Player_Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 玩家进入租赁服事件
type PlayerJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player string `protobuf:"bytes,1,opt,name=Player,proto3" json:"Player,omitempty"` // 玩家名
}

func (x *PlayerJoin) Reset() {
	*x = PlayerJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoin) ProtoMessage() {}

func (x *PlayerJoin) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoin.ProtoReflect.Descriptor instead.
func (*PlayerJoin) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerJoin) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

// 玩家退出租赁服事件
type Player_Left struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player string `protobuf:"bytes,1,opt,name=Player,proto3" json:"Player,omitempty"` // 玩家名
}

func (x *Player_Left) Reset() {
	*x = Player_Left{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player_Left) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player_Left) ProtoMessage() {}

func (x *Player_Left) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player_Left.ProtoReflect.Descriptor instead.
func (*Player_Left) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{5}
}

func (x *Player_Left) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

// 玩家使用菜单功能事件
type Menu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word   []string `protobuf:"bytes,1,rep,name=word,proto3" json:"word,omitempty"`
	Player string   `protobuf:"bytes,2,opt,name=Player,proto3" json:"Player,omitempty"` // 玩家名
}

func (x *Menu) Reset() {
	*x = Menu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{6}
}

func (x *Menu) GetWord() []string {
	if x != nil {
		return x.Word
	}
	return nil
}

func (x *Menu) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

// 玩家私聊机器人事件
type Player_Whisper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player  string `protobuf:"bytes,1,opt,name=Player,proto3" json:"Player,omitempty"`   // 玩家名
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"` // 玩家消息
}

func (x *Player_Whisper) Reset() {
	*x = Player_Whisper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player_Whisper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player_Whisper) ProtoMessage() {}

func (x *Player_Whisper) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player_Whisper.ProtoReflect.Descriptor instead.
func (*Player_Whisper) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{7}
}

func (x *Player_Whisper) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (x *Player_Whisper) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 更新NBT方块事件 BlockActorData
type BlockActorData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *BlockPos `protobuf:"bytes,1,opt,name=Position,proto3" json:"Position,omitempty"`              // 方块位置
	NBT_Data []byte    `protobuf:"bytes,2,opt,name=NBT_Data,json=NBTData,proto3" json:"NBT_Data,omitempty"` // NBT数据
}

func (x *BlockActorData) Reset() {
	*x = BlockActorData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockActorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockActorData) ProtoMessage() {}

func (x *BlockActorData) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockActorData.ProtoReflect.Descriptor instead.
func (*BlockActorData) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{8}
}

func (x *BlockActorData) GetPosition() *BlockPos {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *BlockActorData) GetNBT_Data() []byte {
	if x != nil {
		return x.NBT_Data
	}
	return nil
}

// 系统消息
type System_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NeedsTranslation bool     `protobuf:"varint,1,opt,name=NeedsTranslation,proto3" json:"NeedsTranslation,omitempty"`
	SourceName       string   `protobuf:"bytes,2,opt,name=SourceName,proto3" json:"SourceName,omitempty"`
	Message          string   `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	Parameters       []string `protobuf:"bytes,4,rep,name=Parameters,proto3" json:"Parameters,omitempty"`
	XUID             string   `protobuf:"bytes,5,opt,name=XUID,proto3" json:"XUID,omitempty"`
	PlatformChatID   string   `protobuf:"bytes,6,opt,name=PlatformChatID,proto3" json:"PlatformChatID,omitempty"`
	PlayerRuntimeID  string   `protobuf:"bytes,7,opt,name=PlayerRuntimeID,proto3" json:"PlayerRuntimeID,omitempty"`
}

func (x *System_Message) Reset() {
	*x = System_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *System_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*System_Message) ProtoMessage() {}

func (x *System_Message) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use System_Message.ProtoReflect.Descriptor instead.
func (*System_Message) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{9}
}

func (x *System_Message) GetNeedsTranslation() bool {
	if x != nil {
		return x.NeedsTranslation
	}
	return false
}

func (x *System_Message) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *System_Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *System_Message) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *System_Message) GetXUID() string {
	if x != nil {
		return x.XUID
	}
	return ""
}

func (x *System_Message) GetPlatformChatID() string {
	if x != nil {
		return x.PlatformChatID
	}
	return ""
}

func (x *System_Message) GetPlayerRuntimeID() string {
	if x != nil {
		return x.PlayerRuntimeID
	}
	return ""
}

// q群消息
type Group_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message_ID string `protobuf:"bytes,1,opt,name=Message_ID,json=MessageID,proto3" json:"Message_ID,omitempty"` // 消息ID
	Sender     string `protobuf:"bytes,2,opt,name=Sender,proto3" json:"Sender,omitempty"`                        // 发送者
	Message    string `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`                      // 消息内容
	Time       string `protobuf:"bytes,4,opt,name=Time,proto3" json:"Time,omitempty"`                            // 发送时间
}

func (x *Group_Message) Reset() {
	*x = Group_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Group_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group_Message) ProtoMessage() {}

func (x *Group_Message) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group_Message.ProtoReflect.Descriptor instead.
func (*Group_Message) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{10}
}

func (x *Group_Message) GetMessage_ID() string {
	if x != nil {
		return x.Message_ID
	}
	return ""
}

func (x *Group_Message) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Group_Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Group_Message) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

// 心跳包
type Heart_Beat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"` // 心跳包名称
}

func (x *Heart_Beat) Reset() {
	*x = Heart_Beat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Heart_Beat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heart_Beat) ProtoMessage() {}

func (x *Heart_Beat) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heart_Beat.ProtoReflect.Descriptor instead.
func (*Heart_Beat) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{11}
}

func (x *Heart_Beat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 执行命令
type SendCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string `protobuf:"bytes,1,opt,name=Command,proto3" json:"Command,omitempty"` // 命令内容
}

func (x *SendCmd) Reset() {
	*x = SendCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCmd) ProtoMessage() {}

func (x *SendCmd) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCmd.ProtoReflect.Descriptor instead.
func (*SendCmd) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{12}
}

func (x *SendCmd) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// 发送消息给指定玩家
type Say_To struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player  string `protobuf:"bytes,1,opt,name=Player,proto3" json:"Player,omitempty"`   // 玩家名
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"` // 发送消息内容
}

func (x *Say_To) Reset() {
	*x = Say_To{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Say_To) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Say_To) ProtoMessage() {}

func (x *Say_To) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Say_To.ProtoReflect.Descriptor instead.
func (*Say_To) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{13}
}

func (x *Say_To) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (x *Say_To) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取玩家信息
type Get_Player_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player string `protobuf:"bytes,1,opt,name=Player,proto3" json:"Player,omitempty"` // 玩家名
}

func (x *Get_Player_Info) Reset() {
	*x = Get_Player_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Get_Player_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Player_Info) ProtoMessage() {}

func (x *Get_Player_Info) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Player_Info.ProtoReflect.Descriptor instead.
func (*Get_Player_Info) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{14}
}

func (x *Get_Player_Info) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

// 返回玩家信息
type Return_Player_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Is_True bool                `protobuf:"varint,1,opt,name=Is_True,json=IsTrue,proto3" json:"Is_True,omitempty"` // 是否获取成功
	Message string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`              // 获取失败原因
	Player  *Plugin_Info_Player `protobuf:"bytes,3,opt,name=Player,proto3" json:"Player,omitempty"`                // 玩家信息
}

func (x *Return_Player_Info) Reset() {
	*x = Return_Player_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Return_Player_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Return_Player_Info) ProtoMessage() {}

func (x *Return_Player_Info) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Return_Player_Info.ProtoReflect.Descriptor instead.
func (*Return_Player_Info) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{15}
}

func (x *Return_Player_Info) GetIs_True() bool {
	if x != nil {
		return x.Is_True
	}
	return false
}

func (x *Return_Player_Info) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Return_Player_Info) GetPlayer() *Plugin_Info_Player {
	if x != nil {
		return x.Player
	}
	return nil
}

// 获取在线玩家信息
type Get_Online_Player_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Get_Online_Player_Info) Reset() {
	*x = Get_Online_Player_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Get_Online_Player_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Online_Player_Info) ProtoMessage() {}

func (x *Get_Online_Player_Info) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Online_Player_Info.ProtoReflect.Descriptor instead.
func (*Get_Online_Player_Info) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{16}
}

// 返回在线玩家信息
type Return_Online_Player_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Is_True bool                  `protobuf:"varint,1,opt,name=Is_True,json=IsTrue,proto3" json:"Is_True,omitempty"` // 是否获取成功
	Message string                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`              // 获取失败原因
	Players []*Plugin_Info_Player `protobuf:"bytes,3,rep,name=Players,proto3" json:"Players,omitempty"`              // 在线玩家信息
}

func (x *Return_Online_Player_Info) Reset() {
	*x = Return_Online_Player_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Return_Online_Player_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Return_Online_Player_Info) ProtoMessage() {}

func (x *Return_Online_Player_Info) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Return_Online_Player_Info.ProtoReflect.Descriptor instead.
func (*Return_Online_Player_Info) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{17}
}

func (x *Return_Online_Player_Info) GetIs_True() bool {
	if x != nil {
		return x.Is_True
	}
	return false
}

func (x *Return_Online_Player_Info) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Return_Online_Player_Info) GetPlayers() []*Plugin_Info_Player {
	if x != nil {
		return x.Players
	}
	return nil
}

// 插件版本,采用 x.y.z 命名规则
type Version struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Major int64 `protobuf:"varint,1,opt,name=Major,proto3" json:"Major,omitempty"`
	Minor int64 `protobuf:"varint,2,opt,name=Minor,proto3" json:"Minor,omitempty"`
	Patch int64 `protobuf:"varint,3,opt,name=Patch,proto3" json:"Patch,omitempty"`
}

func (x *Version) Reset() {
	*x = Version{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{18}
}

func (x *Version) GetMajor() int64 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *Version) GetMinor() int64 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *Version) GetPatch() int64 {
	if x != nil {
		return x.Patch
	}
	return 0
}

type Plugin_Info_Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player string `protobuf:"bytes,1,opt,name=Player,proto3" json:"Player,omitempty"` // 玩家名
	UUID   string `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`     // 玩家UUID
}

func (x *Plugin_Info_Player) Reset() {
	*x = Plugin_Info_Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plugin_Info_Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plugin_Info_Player) ProtoMessage() {}

func (x *Plugin_Info_Player) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plugin_Info_Player.ProtoReflect.Descriptor instead.
func (*Plugin_Info_Player) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{19}
}

func (x *Plugin_Info_Player) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (x *Plugin_Info_Player) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

type BlockPos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	Z int32 `protobuf:"varint,3,opt,name=Z,proto3" json:"Z,omitempty"`
}

func (x *BlockPos) Reset() {
	*x = BlockPos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edotcs_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockPos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockPos) ProtoMessage() {}

func (x *BlockPos) ProtoReflect() protoreflect.Message {
	mi := &file_edotcs_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockPos.ProtoReflect.Descriptor instead.
func (*BlockPos) Descriptor() ([]byte, []int) {
	return file_edotcs_proto_rawDescGZIP(), []int{20}
}

func (x *BlockPos) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BlockPos) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BlockPos) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

var File_edotcs_proto protoreflect.FileDescriptor

var file_edotcs_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x65, 0x64, 0x6f, 0x74, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x65, 0x64, 0x6f, 0x74, 0x63, 0x73, 0x22, 0x54, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x5f, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x33, 0x0a, 0x09,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x54, 0x79, 0x70,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x64, 0x6f, 0x74, 0x63,
	0x73, 0x2e, 0x4e, 0x65, 0x77, 0x5f, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x22, 0x9d, 0x02, 0x0a, 0x06, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x29, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x65, 0x64, 0x6f, 0x74,
	0x63, 0x73, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0e, 0x72,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01,
	0x12, 0x20, 0x0a, 0x09, 0x6d, 0x65, 0x6e, 0x75, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x08, 0x6d, 0x65, 0x6e, 0x75, 0x57, 0x6f, 0x72, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x34, 0x0a, 0x13, 0x6d, 0x65, 0x6e, 0x75, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x02, 0x52, 0x12, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x72, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0c, 0x0a, 0x0a, 0x5f,
	0x6d, 0x65, 0x6e, 0x75, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x16, 0x0a, 0x14, 0x5f, 0x6d, 0x65,
	0x6e, 0x75, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x42, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x25, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f,
	0x6a, 0x6f, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x25, 0x0a, 0x0b,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x22, 0x32, 0x0a, 0x04, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x12, 0x0a, 0x04, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x42, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x5f, 0x57, 0x68, 0x69, 0x73, 0x70, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x59, 0x0a, 0x0e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2c, 0x0a,
	0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x65, 0x64, 0x6f, 0x74, 0x63, 0x73, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x6f,
	0x73, 0x52, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x4e,
	0x42, 0x54, 0x5f, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x4e,
	0x42, 0x54, 0x44, 0x61, 0x74, 0x61, 0x22, 0xfc, 0x01, 0x0a, 0x0e, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x5f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x4e, 0x65, 0x65,
	0x64, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x10, 0x4e, 0x65, 0x65, 0x64, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x58, 0x55, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x58,
	0x55, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x43,
	0x68, 0x61, 0x74, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x50, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x43, 0x68, 0x61, 0x74, 0x49, 0x44, 0x12, 0x28, 0x0a, 0x0f, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x49, 0x44, 0x22, 0x74, 0x0a, 0x0d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x20, 0x0a, 0x0a, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x5f, 0x42, 0x65, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x23, 0x0a,
	0x07, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6d, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x22, 0x3a, 0x0a, 0x06, 0x53, 0x61, 0x79, 0x5f, 0x54, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x29,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x5f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x7b, 0x0a, 0x12, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x5f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x17, 0x0a, 0x07, 0x49, 0x73, 0x5f, 0x54, 0x72, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x49, 0x73, 0x54, 0x72, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x65, 0x64, 0x6f, 0x74, 0x63, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x5f, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x84, 0x01, 0x0a, 0x19, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x4f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x5f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17,
	0x0a, 0x07, 0x49, 0x73, 0x5f, 0x54, 0x72, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x49, 0x73, 0x54, 0x72, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x34, 0x0a, 0x07, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x65, 0x64, 0x6f, 0x74, 0x63, 0x73, 0x2e, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0x4b, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x69, 0x6e, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x4d, 0x69, 0x6e, 0x6f, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x50, 0x61, 0x74, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x50,
	0x61, 0x74, 0x63, 0x68, 0x22, 0x40, 0x0a, 0x12, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x49,
	0x6e, 0x66, 0x6f, 0x5f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x22, 0x34, 0x0a, 0x08, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50,
	0x6f, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x58,
	0x12, 0x0c, 0x0a, 0x01, 0x59, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x59, 0x12, 0x0c,
	0x0a, 0x01, 0x5a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x5a, 0x42, 0x2b, 0x5a, 0x29,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x49, 0x6e, 0x6f, 0x74, 0x61,
	0x72, 0x74, 0x2f, 0x65, 0x64, 0x6f, 0x74, 0x63, 0x73, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x5f, 0x73, 0x64, 0x6b, 0x2f, 0x64, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_edotcs_proto_rawDescOnce sync.Once
	file_edotcs_proto_rawDescData = file_edotcs_proto_rawDesc
)

func file_edotcs_proto_rawDescGZIP() []byte {
	file_edotcs_proto_rawDescOnce.Do(func() {
		file_edotcs_proto_rawDescData = protoimpl.X.CompressGZIP(file_edotcs_proto_rawDescData)
	})
	return file_edotcs_proto_rawDescData
}

var file_edotcs_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_edotcs_proto_goTypes = []interface{}{
	(*New_Type)(nil),                  // 0: edotcs.New_Type
	(*TypeList)(nil),                  // 1: edotcs.Type_list
	(*Plugin)(nil),                    // 2: edotcs.Plugin
	(*Player_Message)(nil),            // 3: edotcs.Player_Message
	(*PlayerJoin)(nil),                // 4: edotcs.Player_join
	(*Player_Left)(nil),               // 5: edotcs.Player_Left
	(*Menu)(nil),                      // 6: edotcs.Menu
	(*Player_Whisper)(nil),            // 7: edotcs.Player_Whisper
	(*BlockActorData)(nil),            // 8: edotcs.BlockActorData
	(*System_Message)(nil),            // 9: edotcs.System_Message
	(*Group_Message)(nil),             // 10: edotcs.Group_Message
	(*Heart_Beat)(nil),                // 11: edotcs.Heart_Beat
	(*SendCmd)(nil),                   // 12: edotcs.SendCmd
	(*Say_To)(nil),                    // 13: edotcs.Say_To
	(*Get_Player_Info)(nil),           // 14: edotcs.Get_Player_Info
	(*Return_Player_Info)(nil),        // 15: edotcs.Return_Player_Info
	(*Get_Online_Player_Info)(nil),    // 16: edotcs.Get_Online_Player_Info
	(*Return_Online_Player_Info)(nil), // 17: edotcs.Return_Online_Player_Info
	(*Version)(nil),                   // 18: edotcs.Version
	(*Plugin_Info_Player)(nil),        // 19: edotcs.Plugin_Info_Player
	(*BlockPos)(nil),                  // 20: edotcs.BlockPos
}
var file_edotcs_proto_depIdxs = []int32{
	0,  // 0: edotcs.Type_list.Types:type_name -> edotcs.New_Type
	18, // 1: edotcs.Plugin.Version:type_name -> edotcs.Version
	20, // 2: edotcs.BlockActorData.Position:type_name -> edotcs.BlockPos
	19, // 3: edotcs.Return_Player_Info.Player:type_name -> edotcs.Plugin_Info_Player
	19, // 4: edotcs.Return_Online_Player_Info.Players:type_name -> edotcs.Plugin_Info_Player
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_edotcs_proto_init() }
func file_edotcs_proto_init() {
	if File_edotcs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_edotcs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*New_Type); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypeList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plugin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player_Left); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Menu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player_Whisper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockActorData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*System_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Group_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Heart_Beat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Say_To); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Get_Player_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Return_Player_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Get_Online_Player_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Return_Online_Player_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Version); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plugin_Info_Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edotcs_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockPos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_edotcs_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_edotcs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_edotcs_proto_goTypes,
		DependencyIndexes: file_edotcs_proto_depIdxs,
		MessageInfos:      file_edotcs_proto_msgTypes,
	}.Build()
	File_edotcs_proto = out.File
	file_edotcs_proto_rawDesc = nil
	file_edotcs_proto_goTypes = nil
	file_edotcs_proto_depIdxs = nil
}
